version: '3.9'
services:
  my-sql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: testnest
    volumes:
      - ./data/mysql:/var/lib/mysql
      